if (NOT DEFINED INPUT_BUNDLE OR INPUT_BUNDLE STREQUAL "")
   message(FATAL_ERROR "INPUT_BUNDLE is required")
endif()

if (NOT EXISTS "${INPUT_BUNDLE}")
   message(FATAL_ERROR "Input bundle does not exist: ${INPUT_BUNDLE}")
endif()

if (NOT DEFINED OUTPUT_SHA256 OR OUTPUT_SHA256 STREQUAL "")
   message(FATAL_ERROR "OUTPUT_SHA256 is required")
endif()

file(SHA256 "${INPUT_BUNDLE}" PRODIGY_BUNDLE_SHA256)
string(TOLOWER "${PRODIGY_BUNDLE_SHA256}" PRODIGY_BUNDLE_SHA256)
file(WRITE "${OUTPUT_SHA256}" "${PRODIGY_BUNDLE_SHA256}\n")
