[package]
name = "prodigy-noise"
version = "0.1.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
snow = { path = "vendor/snow", default-features = false, features = ["default-resolver", "use-curve25519", "use-chacha20poly1305", "use-sha2", "use-getrandom", "risky-raw-split"] }
zeroize = { version = "1.8", default-features = false }
